name: Build Resumes
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LaTeX with FontAwesome
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            latexmk

      - name: Build IT Resume
        run: make it

      - name: Build TechArt Resume
        run: make techart

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: exports/*.pdf
          retention-days: 90
